site_name: AcmeN Docs
theme: readthedocs
docs_dir: raw
site_dir: docs
copyright: copyright (c) 2020 Huo Jiacheng

nav:
    - 主页: index.md
    - 开发者: developer.md
    - 致谢: acknowledgment.md
    - ChangeLog: changelog.md
markdown_extensions: 
    - toc:
        permalink: True

plugins:
    - search:
        lang: en
        prebuild_index: python