site_name: AcmeN Docs
theme: readthedocs
docs_dir: raw
site_dir: docs
copyright: copyright (c) 2020-2022 Huo Jiacheng

nav:
    - 主页: index.md
    - 开发: 
        - DNS: developer/dns.md
        - 网络IO: developer/acme_net_io.md
        - ChallengeHandling: developer/challenge_handlers/index.md
    - 其他:
        - 致谢: acknowledgment.md
        - ChangeLog: changelog.md
markdown_extensions: 
    - toc:
        permalink: True

plugins:
    - search:
        lang: en
        prebuild_index: python
